import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import PageTransition from "@/components/pageTransition";
import Staireffect from "@/components/Staireffect";
const inter = Inter({ subsets: ["latin"] });
const JetBrainsMono= JetBrains_Mono({
   subsets:['latin'],
   weight:['100','200','300','400','500','600','700','800'],
   variable:'--font-jetbrainMono'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header/>
        <Staireffect/>
        <PageTransition> {children}</PageTransition>
        </body>
    </html>
  );
}
